### ISSUE TITLE
Suggestion: Add double\triple bottom

### ISSUE THREAD

**Issue by oneofthehorses** [matiaskorhonen/paper-age#105]
Hello!

Thanks for your work! Suggest to develop project little bit further:
To hide 3 or more secrets under one QR-code, where each password response\decrypt for different secred and it's impossible to proof there something more than just 1 secret in it... LIke in library here ->

https://github.com/sunknudsen/blockcrypt + https://github.com/sunknudsen/blockcrypt/blob/master/src/index.ts

I'm bad in coding but i could help with translation to few languages and making logo

Cheers!

**Comment by matiaskorhonen** [comment]
Hi, thanks for your suggestion. 

However, that feature is out of scope for the problems that PaperAge attempts to solve.

The problem domain that PaperAge targets is making backups using encryption that's been validated by folks who know far more about cryptography than I do. Obfuscation or plausible deniability is not something that can be trivially added.

If you're facing an adversary who can compel decryption by prosecution (or a [$5 wrench](https://xkcd.com/538/) for that matter), this project is not for you. For more information, see the [Threat models and use cases](https://github.com/matiaskorhonen/paper-age?tab=readme-ov-file#threat-models-and-use-cases) section in the README.
