### ISSUE TITLE
Possible Windows issue

### ISSUE THREAD

**Issue by matiaskorhonen** [matiaskorhonen/paper-age#110]
The Windows build might be broken. Windows 7 is not going to be a supported version but the latest paper-age build should be tested in Windows 11 or 10…

> Windows 7 x64, paper-age 1.2.0
> 
> ```console
> $ paper-age.exe LICENSE.txt
> Error: Custom { kind: Other, error: "The handle is invalid. (os error 6)" }
> ```
>
> _Originally posted by @sergeevabc in https://github.com/matiaskorhonen/paper-age/issues/17#issuecomment-1902808058_

**Comment by matiaskorhonen** [comment]
Tested the latest release on a Windows Server 2022 remote desktop and it worked as expected. 

The test suite also passes on Windows with GitHub Actions.

**Comment by sergeevabc** [comment]
I see the same error on my end.

**Comment by matiaskorhonen** [comment]
@sergeevabc If this remains an issue on an supported version of Windows, please open a new issue. So far I've been unable to reproduce the issue on a recent version of Windows and the test suite passes on Windows, so there's little else I can do about it.

I'm just a solo developer doing this in my free time, so I'm sorry, but there's just no way I'm going to spend time investigating issues on a platform for which support ended 4 years ago.

Passive aggressively linking to “security mindset” search results isn't doing you any favours here.  Feel free to use the `age` command with any QR encoder of your choice if this project isn't meeting your needs…
