### ISSUE TITLE
Small GUI and multiplatform release? [Proposal]

### ISSUE THREAD

**Issue by iuvi7** [matiaskorhonen/paper-age#156]
Hey! Cool project

Wish to ask:

+ If there any plans to make Small GUI and multiplatform release, for example AppImage, Deb, Flatpak or probably one page HTML version? So users can visually can works with it not only from CLI

+ Any plans to release .apk file for Android to generate\scan protected QR's and decrypt them?

I could help with translations on other languages ;)

Thanks!

**Comment by matiaskorhonen** [comment]
Sorry, GUIs are outside of the scope of this project
