### ISSUE TITLE
Feature Request: Ability to hide "Passphrase: ___"  and show time

### ISSUE THREAD

**Issue by bsdayo** [matiaskorhonen/paper-age#88]
This is an awesome project! I've used it to encrypt some stuff. I have some feature requests:

- Add an option to hide the "Passphrase: ___" part. I don't really want to write my passphrase on paper, but having an empty fill-in-the-blank makes me feel uncomfortable. I'd like to have the option to leave it out.
- Add a display of the time so the paper can show at what point the file was encrypted. (Maybe also a option to control whether to enable this feature?)

~~Since I don't know Rust at all, there's no way for me to implement them and then submit a PR 😟. I sincerely hope you'll take my suggestions!~~

edit: Learned some basis about Rust and implemented in #89

**Comment by bsdayo** [comment]
btw another problem is that the armor text is not centered...? That asymmetry brings a strange feeling.

<img width="514" alt="image" src="https://github.com/matiaskorhonen/paper-age/assets/41754841/4022917d-d284-4dc7-bc1e-e4f8f298bf94">

**Comment by matiaskorhonen** [comment]
The fields/text below the QR code is now more configurable so it's now possible to have arbitrary text there.

e.g. `paper-age --notes-label="Created at: $(date -Iseconds)" --skip-notes-line` will add the current time to the PDF.
